### ISSUE TITLE
Cannot extract icons from SHELL32.dll

### ISSUE THREAD

**Issue by RixInGithub** [firodj/extract-icon-py#10]
I traversed around the code, and I got this as should-work code:
```py
import extract_icon as icns

ext = icns.ExtractIcon(r"C:\Windows\System32\SHELL32.dll")
foldIcon = ext.get_group_icons()[3]
foldPIL = ext.export(foldIcon, index=0)
foldPIL.save("foldIcon.ico")
print("Icon extracted successfully.")
```
But it just throws the error
```diff
- Traceback (most recent call last):
-   File "C:\Users\user\Downloads\whistle\icns.py", line 4, in <module>
-     foldIcon = ext.get_group_icons()[3]
-                ^^^^^^^^^^^^^^^^^^^^^
-   File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\extract_icon\__init__.py", line 57, in get_group_icons
-     rt_base_dir = self.find_resource_base('RT_GROUP_ICON')
-                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-   File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\extract_icon\__init__.py", line 22, in find_resource_base
-     entry in self.pe.DIRECTORY_ENTRY_RESOURCE.entries].index(
-                                                        ^^^^^^
- ValueError: 14 is not in list
```
Does someone have an answer to this chaos?

**Comment by firodj** [comment]
Hi @RixInGithub, I doubt it works well on Python 3.x (seen from the path you share). What version you use specifically?

I'll try to check later.

**Comment by RixInGithub** [comment]
> Hi @RixInGithub, I doubt it works well on Python 3.x (seen from the path you share). What version you use specifically?
> 
> I'll try to check later.

3.11, why do you ask?

**Comment by firodj** [comment]
Your dll `SHELL32.dll` doesnt have `RT_GROUP_ICON` resource entry which the extract-icon expect. May I know the version of your SHELL32.dll?

**Comment by RixInGithub** [comment]
> Your dll `SHELL32.dll` doesnt have `RT_GROUP_ICON` resource entry which the extract-icon expect. May I know the version of your SHELL32.dll?

Nevermind, I found a solution using [`icoextract`](https://pypi.org/project/icoextract)
