### ISSUE TITLE
Extracting less icons then whats in the file

### ISSUE THREAD

**Issue by DZKeeper** [firodj/extract-icon-py#2]
Hi,

Thanks for this great project. I am facing a problem, in a sense that a PE file i am trying to extract icon out of, contains 17 icons in total, however, using your project I only get 9 out of it.

Here is my code:

```python
from extract_icon import *
from PIL import Image, ImageChops
import sys

extractor = ExtractIcon(sys.argv[1])
groups = extractor.get_group_icons()
for i in xrange(len(groups[0])):
    icon = groups[0][i]
    iconexport = extractor.export(groups[0], i)
    iconexport.save("icons/" + str(i) + ".ico")
```

I believe my problem is related to the comment in your code on line 45 and 46:

```
# another Directory 
# probably language take the first one
```

and this is what the icon section looks in CFF Explorer:

![image](https://user-images.githubusercontent.com/6238126/35307572-4a8b24fa-0071-11e8-903e-4387302ad2fa.png)

I believe the 1033 refers to language ? is that possible ?

Thank you for your time, this not much of an issue, but rather a request for help.

**Comment by firodj** [comment]
Hi @DZKeeper, sorry for late reply, currently I don't have time to inspect it but yes 1033 is Locale ID for English United States (Default English Locale ID). And in some cases there are many executables that some icons not extracted. So, there still need improvements.
