### ISSUE TITLE
Can icon be externalize from .rsrc section and not part of the signature ? 

### ISSUE THREAD

**Issue by iradization** [firodj/extract-icon-py#3]
Hi, 

I was wondering if there's a way to somehow externalize the .rsrc section from the pe file, so it's not be part of the signature. 

Perhaps do you know of a way to specify an external path of a valid .ico file anywhere in the PE file ? maybe there's an API for this ? 

I've read the documentation of the manifest embedded xml inside the .rsrc, but couldn't find and configuration do so ... 

thanks !

**Comment by firodj** [comment]
I'm not sure,  might be you want  PE  overlay? anyhow I need to close this issue, thanks.
